version: '3'
services:
  php-fpm:
    build:
        context: .
        dockerfile: Dockerfile.worker
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: sh -c "composer install && php-fpm"
    networks:
      - laravel
  web:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php-fpm
    links:
      - php-fpm
    networks:
      - laravel
#   mysql:
#     image: 'mysql:5.7'
#     environment:
#       MYSQL_DATABASE: laravel
#       MYSQL_ROOT_PASSWORD: secret
#     ports:
#       - '3307:3306'
#     networks:
#       - laravel
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_root_username
      - MONGO_INITDB_ROOT_PASSWORD=mongo_root_password
    networks:
      - laravel
    secrets:
      - mongo_root_username
      - mongo_root_password
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo_root_username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo_root_password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    secrets:
      - mongo_root_username
      - mongo_root_password
    depends_on:
      - mongodb
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
